version: "3.8"

services:
  frontend:
    volumes:
      - type: bind
        source: ./frontend
        target: /workspace/frontend

  backend-elixir:
    volumes:
      - type: bind
        source: ./backend/elixir
        target: /workspace/backend/elixir

  backend-python:
    volumes:
      - type: bind
        source: ./backend/python
        target: /workspace/backend/python

  backend-java:
    volumes:
      - type: bind
        source: ./backend/java
        target: /workspace/backend/java
