version: "3.8"

services:
  frontend:
    volumes:
      - type: bind
        source: .
        target: .

  backend-elixir:
    volumes:
      - type: bind
        source: .
        target: /workspace
      - type: volume
        source: backend-python
        target: /workspace/backend/python
      - type: volume
        source: backend-java
        target: /workspace/backend/java

  backend-python:
    volumes:
      - type: bind
        source: .
        target: /workspace
      - type: volume
        source: backend-elixir
        target: /workspace/backend/elixir
      - type: volume
        source: backend-java
        target: /workspace/backend/java

  backend-java:
    volumes:
      - type: bind
        source: .
        target: /workspace
      - type: volume
        source: backend-elixir
        target: /workspace/backend/elixir
      - type: volume
        source: backend-python
        target: /workspace/backend/python

volumes:
  backend-elixir:
  backend-python:
  backend-java: