CREATE TABLE IF NOT EXISTS creatorlink.users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cognito_sub VARCHAR(50) NOT NULL UNIQUE,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    phone_number VARCHAR(15),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON COLUMN creatorlink.users.cognito_sub IS 'AWS Cognito User ID';

CREATE TABLE IF NOT EXISTS creatorlink.user_profiles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    bio TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES creatorlink.users(id) ON DELETE CASCADE
);

ALTER TABLE creatorlink.users OWNER TO creatorlink;
ALTER TABLE creatorlink.user_profiles OWNER TO creatorlink;